name: test min schedule
on:
  schedule:
    - cron: '* * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          ref: develop
      - name: Install dependencies
        run: echo "test me"