name: Deploy DoD Datasets
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'


jobs:

  deploy_dod:
    name: Deploy DoD as Scheduled Datasets
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Build and persist dataset locally
        run: |
          python deploy_dod_dataset.py